font_family IosevkaTerm Nerd Font
font_size   12

foreground            #D8D1D3
background            #060708
cursor                #BAB7B6
cursor_text_color     #060708
selection_foreground  #060708
selection_background  #BAB7B6
url_color             #8E8A8C

color0  #1B2124
color8  #464D52
color1  #8F1E25
color9  #CC1E2B
color2  #7D8F9C
color10 #9AABB7
color3  #BAB7B6
color11 #D8D1D3
color4  #5E7A8F
color12 #7F9BB0
color5  #8A616D
color13 #A07F8C
color6  #6F8C96
color14 #8FAAB3
color7  #BAB7B6
color15 #E4DFE1

background_opacity    0.69
window_padding_width  10
cursor_shape          beam
cursor_trail          3
hide_window_decorations yes

confirm_os_window_close 0
enable_audio_bell       no
scrollback_lines        5000
copy_on_select          clipboard
tab_bar_style           hidden

cursor_blink_interval 0
repaint_delay         6
input_delay           2
sync_to_monitor       yes

map ctrl+shift+enter new_window_with_cwd
map ctrl+equal       change_font_size all +1.0
map ctrl+minus       change_font_size all -1.0
