[theme]
background = "#060708"
primary = "#D8D1D3"
secondary = "#8E8A8C"
title = "#CC1E2B"
playing = "#BAB7B6"
playing_selected = "#D8D1D3"
playing_bg = "#060708"
highlight = "#060708"
highlight_bg = "#BAB7B6"
error = "#D8D1D3"
error_bg = "#8F1E25"
statusbar = "#BAB7B6"
statusbar_progress = "#BAB7B6"
statusbar_bg = "#101316"
cmdline = "#D8D1D3"
cmdline_bg = "#060708"
search_match = "#CC1E2B"

[keybindings]
"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"l" = "move right 1"
